# Generated by Django 2.2.8 on 2020-01-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='company',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='agent',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='agent',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
